- name: Configuring Docker
  hosts: web
  tasks:
  - name: Adding the Docker repo to managed node
    yum_repository:
      name: docker
      description: Docker YUM Repo
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
      gpgcheck: no
    register: a

  - name: Checking the status of yum repo
    debug:
      var: a.failed

  - name: installing Docker packages
    package:
      name:
        - docker-ce-3:18.09.1-3.el7.x86_64
        - containerd.io-1.2.0-3.el7.x86_64 
      state: latest
    register: b
    when: a.failed == false

  - name: Checking the installation of Docker
    debug:
      var: b.failed

  - name: starting docker service
    service:
      name: "docker"
      state: "started"
      enabled: yes
    register: c
    when: b.failed == false
 
  - name: Checking the status service
    debug:
      var: c.failed

